
# POST Request 
POST http://localhost:1017/api/users
Content-Type: application/json

{
  "username": "John_doe",
  "password": "password123",
  "name": "John Doe",
  "email": "john@example.com",
  "homeAddress": "123 Main St"
}

# GET Request 
GET http://localhost:1017/api/user/123/john_doe

# PUT Request
PUT http://localhost:1017/api/users/john_doe
Content-Type: application/json

{
    "name": "Updated Name",
    "homeAddress": "456 Elm St"
}


# POST Request to Create a Credit Card 
POST http://localhost:1017/api/credit-cards
Content-Type: application/json

{
    "userName": "John_doe",
    "cardNumber": "1234-5678-9012-3456",
    "expirationDate": "12/25",
    "cvv": "123"
}
